//#include "./palcomStyle.h"

#include "./defaultButtonStyle.h"
#include "./defaultTextareaStyle.h"
#include "./defaultImagebuttonStyle.h"
#include "./defaultPopupStyle.h"
#include "./defaultTextInputStyle.h"
#include "./defaultTabmenuStyle.h"
#include "./defaultMenuStyle.h"
#include "./pinPadButton.style.h"
